### ISSUE TITLE
Cannot run tox command

### ISSUE THREAD

**Issue by namnh68** [locvx1234/sample-tox#1]
Currently, I cannot run the command "tox -e loc".
Here is output:

Processing ./.tox/dist/sample-1.0.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-aioyo8tl-build/setup.py", line 9, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/home/minhkma/sample-tox/.tox/loc/lib/python3.5/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-aioyo8tl-build/README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-aioyo8tl-build/

loc installed: attrs==17.4.0,flake8==3.5.0,mccabe==0.6.1,pkg-resources==0.0.0,pluggy==0.6.0,py==1.5.2,pycodestyle==2.3.1,pyflakes==1.6.0,pytest==3.4.1,six==1.11.0
================
Do you run the command successfully?

**Comment by locvx1234** [comment]
you must run the `python setup.py install` first to install environment
